### Métodos Numéricos Computacionales
#### Prácticas computacionales de "Solución de sistemas de ecuaciones lineales"

Instrucciones para los Ejercicios

1. **Trabajo en Grupo:**
   - Los ejercicios deben ser resueltos y entregados en grupo.
   - La cantidad de integrantes por grupo será definida el día de la actividad, así como la fecha límite para la entrega.

2. **Uso de Google Colab y Compartir:**
   - Este notebook debe ser copiado al GitHub o Google Drive de alguno de los integrantes del grupo.
   - El grupo será responsable de programar las soluciones, realizar las pruebas y enviar el trabajo final al profesor.

3. **Implementación de los Ejercicios:**
   - Cada ejercicio debe ser implementado de manera que cumpla con los objetivos específicos descritos en cada problema.
   - El código debe devolver claramente la información calculada de acuerdo a lo solicitado.

4. **Calidad del Código:**
   - El código debe ejecutarse sin errores.
   - Es obligatorio incluir **comentarios explicativos** para describir las ideas y conceptos implícitos en el código, facilitando la comprensión de su lógica.

5. **Envío del Trabajo:**
   - Una vez completado, el notebook debe ser enviado a través de Moodle.
   - En caso de dudas, pueden contactarme por correo electrónico a **marcelo.danesi@utec.edu.uy**.

6. **Orientaciones Adicionales:**
   - Asegúrense de que todas las celdas de código hayan sido ejecutadas antes de enviar.
   - Incluyan el nombre completo y correo electrónico de todos los integrantes al inicio del notebook.
   - Si utilizan referencias externas, menciónenlas de forma adecuada.

¡Buena suerte y aprovechen la práctica para consolidar los conceptos de métodos numéricos!

#### **Métodos directos**

En la clase anterior, abordamos métodos algebraicos para la resolución de matrices, pero ¿cómo podemos trasladar este problema de encontrar la solución directa a Python? A continuación, veremos un ejemplo y algunos ejercicios que nos prepararán para la implementación de métodos iterativos, como el método de Jacobi y Gauss-Seidel.

##### **Ejemplo 1: Resolución de un sistema de ecuaciones lineales**


**Descripción del problema:**

Considere el sistema de ecuaciones lineales representado por la matriz

$$A = \left[
\begin{array}{rrr|r}
4 & -1 & 2 \\
0 & -3 & 1  \\
-1 & 2 & 5  
\end{array}
\right]$$

y el vector

$$b =\left[
\begin{array}{c}
15  \\
6  \\
11  
\end{array}
\right]$$

en la ecuación $Ax = b$. Nuestro objetivo es encontrar la solución exacta del sistema utilizando Python.

**Objetivo:**
- Implementar la resolución del sistema usando la función `numpy.linalg.solve`.
- Verificar la solución obtenida.

**Salidas:**
1. El vector solución $x$.


**Ejemplo de salida esperada:**

$\text{Solución}: [ 2. -1.  3.]$

In [ ]:
import numpy as np

# Definimos la matriz de coeficientes A
A = np.array([
    [4, -1, 2],
    [0, -3, 1],
    [-1, 2, 5]
], dtype=float)

# Definimos el vector de términos independientes b
b = np.array([15, 6, 11], dtype=float)

# Resolvemos el sistema de ecuaciones Ax = b
x = np.linalg.solve(A, b)

# Mostramos la solución obtenida
print("Solución:", x)

Solución: [ 2. -1.  3.]


##### **Ejemplo 2: Triangularización superior con `numpy.triu`**


**Descripción del problema:**

Utilice la función `numpy.triu` para obtener la forma triangular superior de la matriz

$$A = \left[
\begin{array}{rrr}
4 & -1 & 2 \\
0 & -3 & 1  \\
-1 & 2 & 5  
\end{array}
\right].$$


**Objetivo:**
- Extraer la matriz triangular superior.

**Salidas:**
1. Matriz triangular superior.


In [ ]:
import numpy as np

# Definimos la matriz de coeficientes A
A = np.array([
    [4, -1, 2],
    [0, -3, 1],
    [-1, 2, 5]
], dtype=float)

# Obtenemos la matriz triangular superior
A_triu = np.triu(A)

# Mostramos el resultado
print("Matriz triangular superior:")
print(A_triu)

Nos ejercicios a seguir, considere sempre a matriz

$$A = \left[
\begin{array}{rrr}
0 & 2 & -1 \\
1 & 1 & 4  \\
6 & -2 & 3  
\end{array}
\right].$$


##### **Ejercicio 1: Triangularización inferior con `numpy.tril`**

**Descripción del problema:**

Utilice la función `numpy.tril` para obtener la forma triangular inferior de la matriz dada $A$.

**Objetivo:**
- Extraer la matriz triangular inferior.

**Salidas:**
1. Matriz triangular inferior.

In [1]:
import numpy as np

# Definimos la matriz de coeficientes A
A = np.array([
    [0, 2, -1],
    [1, 1, 4],
    [6, -2, 3]
], dtype=float)

# Obtenemos la matriz triangular superior
A_tril = np.tril(A)

# Mostramos el resultado
print("Matriz triangular inferior:")
print(A_tril)

Matriz triangular inferior:
[[ 0.  0.  0.]
 [ 1.  1.  0.]
 [ 6. -2.  3.]]


##### **Ejercicio 2: Factorización LU con `scipy.linalg.lu`**

**Descripción del problema:**

Utilice `scipy.linalg.lu` para descomponer la matriz fija $A$ en sus componentes $L$ y $U$. En caso de dudas sobre el uso del comando, consulte la documentación oficial de la biblioteca SciPy.

**Objetivo:**
- Descomponer la matriz en factores triangulares inferior y superior.

**Salidas:**
1. Matriz triangular inferior $L$.
2. Matriz triangular superior $U$.

In [3]:
import numpy as np
import scipy.linalg

# Definimos la matriz de coeficientes A
A = np.array([
    [0, 2, -1],
    [1, 1, 4],
    [6, -2, 3]
], dtype=float)

# Obtenemos la matriz triangular superior
p, L,U = scipy.linalg.lu(A)

# Mostramos el resultado
print("Matriz L:")
print(L)
print("Matriz u:")
print(U)

Matriz L:
[[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.16666667 0.66666667 1.        ]]
Matriz u:
[[ 6.         -2.          3.        ]
 [ 0.          2.         -1.        ]
 [ 0.          0.          4.16666667]]


##### **Ejercicio 3:  Intercambio de filas en la matriz**

**Descripción del problema:**

Manipule las líneas de la matriz $A$ dada a fin de obtener una nueva matriz $B$ que tenga las filas de índice 0 y 2 intercambiadas usando el comando B[[0,2]] = A[[2,0]].

**Objetivo:**
- Reordenar las filas de la matriz.

**Salidas:**
1. Matriz $B$ con filas intercambiadas.

In [5]:
# Definimos la matriz de coeficientes A
A = np.array([
    [0, 2, -1],
    [1, 1, 4],
    [6, -2, 3]
], dtype=float)

B=A.copy()
B[0],B[2] = A[2],A[0]

print("matriz A")
print(A)
print("matriz B")
print(B)


matriz A
[[ 0.  2. -1.]
 [ 1.  1.  4.]
 [ 6. -2.  3.]]
matriz B
[[ 6. -2.  3.]
 [ 1.  1.  4.]
 [ 0.  2. -1.]]


##### **Ejercicio 4 (difícil): Transformación a matriz estrictamente diagonalmente dominante**

**Descripción del problema:**

Determine una nueva matriz $B$ a partir de $A$ que sea estrictamente diagonalmente dominante mediante el reordenamiento de las filas. Saiba que una matriz es estrictamente diagonalmente dominante si el módulo de cada elemento de la diagonal principal es mayor que la suma de los módulos de los elementos de su fila. **Tarea adicional**: piense e implemente una estrategia para realizar este ordenamiento para cualquier matriz $A$.

**Objetivo:**
- Reorganizar las filas de la matriz para hacerla estrictamente diagonalmente dominante.

**Salidas:**
1. Matriz $B$ reordenada.

In [6]:
import numpy as np

# Función para verificar si la matriz es estrictamente diagonalmente dominante
def es_diagonalmente_dominante(A):
    filas, columnas = A.shape
    suma_diagonal = 0
    for i in range(filas):
        suma_no_diagonal =0
        for j in range(filas):
          if i != j:
            suma_no_diagonal = suma_no_diagonal + abs(A[i,j])
        suma_diagonal = abs(A[i,i])
        if suma_diagonal <= suma_no_diagonal:
            return False
    return True

# Función para reordenar las filas de la matriz para que sea estrictamente diagonalmente dominante
def reordenar_matriz(A):
    filas, columnas = A.shape
    B = A.copy()  # Hacemos una copia de A para no modificarla directamente

    # Intentamos reordenar las filas para hacer la matriz diagonalmente dominante
    for i in range(filas):
        # Seleccionamos la fila con el valor absoluto más grande en la columna i (sin considerar la diagonal)
        max_fila_idx = i
        max_valor = np.abs(B[i, i])

        for j in range(i + 1, filas):
            if np.abs(B[j, i]) > max_valor:
                max_fila_idx = j
                max_valor = np.abs(B[j, i])

        # Si encontramos una fila con un mayor valor absoluto, intercambiamos las filas
        if max_fila_idx != i:
            B[[i, max_fila_idx], :] = B[[max_fila_idx, i], :]

    # Si la matriz reordenada es diagonalmente dominante, devolvemos la matriz resultante
    if es_diagonalmente_dominante(B):
        return B
    else:
        raise ValueError("No es posible hacer la matriz estrictamente diagonalmente dominante con el reordenamiento de filas.")

# Ejemplo de uso
A = np.array([
    [0, 2, -1],
    [1, 1, 4],
    [6, -2, 3]
], dtype=float)

print("Matriz original A:")
print(A)

# Reordenamos la matriz para hacerla estrictamente diagonalmente dominante
try:
    B = reordenar_matriz(A)
    print("\nMatriz B (reordenada y estrictamente diagonalmente dominante):")
    print(B)
except ValueError as e:
    print("\nError:", e)


Matriz original A:
[[ 0.  2. -1.]
 [ 1.  1.  4.]
 [ 6. -2.  3.]]

Matriz B (reordenada y estrictamente diagonalmente dominante):
[[ 6. -2.  3.]
 [ 0.  2. -1.]
 [ 1.  1.  4.]]


##### **Ejercicio 5: Cálculo de una secuencia definida por una matriz**

**Descripción del problema:**

Calcule los términos de la secuencia definida por $A_n = A^n - 1/2*I$, donde $I$ es la matriz identidad, recibiendo como entrada el valor de $n$.

**Objetivo:**
- Calcular la secuencia definida a partir de la matriz $A$.

**Entradas:**
1. Número natural $n$.

**Salidas:**
1. Matriz resultante $A_n$.

In [6]:
import numpy as np

# Define la matriz A
A = np.array([
    [0, 2, -1],
    [1, 1, 4],
    [6, -2, 3]
], dtype=float)

def calcular_secuencia(n):
    A_n = A.copy()  # Copia de la matriz A
    for i in range(1, n):
        A_n = np.dot(A_n,A)
    return A_n

# Ejemplo de uso
n = int(input("Ingrese n : "))  # Número de iteraciones

A_n = calcular_secuencia(n)
# Crea la matriz identidad
I = np.eye(3)

# Calcula 1/2 * I
media_I = 0.5 * I
A_n = A_n - media_I
print(f"Matriz A :")
print(A)
print(f"Matriz resultante A_{n}:")
print(A_n)



Ingrese n : 1
Matriz A :
[[ 0.  2. -1.]
 [ 1.  1.  4.]
 [ 6. -2.  3.]]
Matriz resultante A_1:
[[-0.5  2.  -1. ]
 [ 1.   0.5  4. ]
 [ 6.  -2.   2.5]]
Matriz resultante A = L*U
[[ 2.  0.  1. -1.]
 [ 1.  3.  0.  1.]
 [-2.  0.  3.  0.]
 [ 0. -2.  1. -1.]]


#### **Métodos Iterativos: método de Jacobi**

Los "Métodos Iterativos" constituyen una clase de técnicas numéricas para resolver sistemas de ecuaciones lineales, en las cuales la solución exacta $x$ se obtiene como el límite de una secuencia de aproximaciones $x^{(0)}, x^{(1)}, \ldots$. Estos métodos son particularmente útiles cuando las matrices de los sistemas poseen características especiales, como ser grandes y dispersas (es decir, contener muchos elementos nulos).

A diferencia de los métodos directos, que buscan la solución exacta en un número fijo de pasos, los métodos iterativos construyen aproximaciones sucesivas, reduciendo el costo computacional en cada etapa.

En esta sección, estudiaremos el método de Jacobi, una técnica iterativa ampliamente utilizada.


##### **Ejemplo 1: Aplicación del método de Jacobi**



**Descripción del problema:**

Apliquemos el método de Jacobi al siguiente sistema de ecuaciones:
$$
\left\{
\begin{array}{rcc}
4x_1  -x_2  +2x_3 & = & 15\\
  -3x_2  +x_3 & = & 6\\
-x_1  +2x_2  +5x_3 & = & 11
\end{array}
\right.
$$

y calculemos las 4 primeras aproximaciones $x^{(1)}, x^{(2)}, x^{(3)}, x^{(4)}$ tomando como aproximación inicial $x^{(0)}$ el vector nulo.

**Objetivo:**
- Implementar el método de Jacobi iterativamente.
- Comparar las aproximaciones con la solución exacta.

**Salidas:**
1. Aproximaciones $x^{(1)}, x^{(2)}, x^{(3)}, x^{(4)}$.

In [ ]:
import numpy as np

A = np.array([
    [4, -1, 2],
    [0, -3, 1],
    [-1, 2, 5]
], dtype=float)

b = np.array([15, 6, 11], dtype=float)

# Aproximación inicial
x = np.zeros_like(b, dtype=float)

# Número de iteraciones
num_iteraciones = 4

# Matriz diagonal D
D = np.diag(np.diag(A))
D_inv = np.linalg.inv(D)
N = D - A

# Iteraciones de Jacobi
for k in range(num_iteraciones):
    x = np.dot(D_inv, np.dot(N, x) + b)
    print(f"Iteración {k+1}: {x}")

En la recta real, la distancia entre dos puntos se mide utilizando el valor absoluto. En espacios reales de dimensión mayor, la noción de distancia se generaliza mediante la norma euclidiana, es decir, si $x=(x_1, \ldots, x_n)$ e $y=(y_1, \ldots,y_n) \in \mathbb{R}^n $ entonces

$$||x-y|| = \left(\sum_{i=1}^n(x_i-y_i)^2\right)^{1/2}. $$

Esta medida nos permite evaluar la magnitud de un vector y su proximidad a otros puntos en el espacio. A continuación, mostramos cómo calcular esta norma usando Python.

##### **Ejemplo 2: Cálculo de la norma euclidiana**

**Descripción del problema:**

Calcular la norma euclidiana de un vector en $\mathbb{R}^n$.

**Objetivo:**
- Aplicar la función `np.linalg.norm` para calcular la norma de un vector.

**Salidas:**
1. Valor de la norma euclidiana.

In [ ]:
import numpy as np

# Definimos un vector
x = np.array([3, 4, 5])

# Calculamos la norma euclidiana
norma = np.linalg.norm(x)

print("Norma euclidiana del vector:", norma)

##### **Ejercicio 1: Implementación del método de Jacobi con criterio de convergencia**

**Descripción del problema:**

Implemente una función en Python que aplique el método de Jacobi para resolver el sistema de ecuaciones
$$
\left\{
\begin{array}{rcc}
5x_1  -2x_2  +3x_3 & = & 8\\
3x_1   +8x_2  -4x_3 & = & 10\\
x_1  -5x_2  +7x_3 & = & 6
\end{array}
\right.
$$
hasta alcanzar una tolerancia de $10^{-4}$.

**Objetivo:**
- Implementar iteraciones hasta la convergencia utilizando la norma euclidiana.

**Salidas:**
1. Vector solución aproximada.

##### **Ejercicio 2: Análisis de convergencia del método de Jacobi**

**Descripción del problema:**

No todas las matrices de coeficientes garantizan la convergencia del método de Jacobi hacia la solución exacta del sistema. Use el código desarrollado en el ejercicio anterior para observar los vectores $x^{(0)}, x^{(1)}, \ldots$ generados por el método de Jacobi cuando se aplica a los siguientes:
```python
A = np.array([[1, 3, -2], [2, 6, -4], [-1, -3, 2]], dtype=float)
b = np.array([5, 9, -4], dtype=float)
```


**Objetivo:**
- Analizar si la secuencia generada por el método de Jacobi converge o diverge.
- Reflexionar sobre la preparación del código para manejar situaciones de divergencia.

**Salidas:**

El estudiante debe analizar las iteraciones obtenidas e identificar si la secuencia muestra un comportamiento creciente o errático, indicando falta de convergencia.


##### **Ejercicio 3: Comparación de normas para evaluar la convergencia**


**Descripción del problema:**

El criterio de convergencia del método de Jacobi puede evaluarse utilizando diferentes normas vectoriales. En este ejercicio, se comparará el desempeño del método utilizando la norma euclidiana (L2), la norma del máximo (L∞) y la norma uno (L1).

**Objetivo:**
- Implementar el método de Jacobi con diferentes normas de convergencia.
- Comparar el número de iteraciones necesarias según la norma utilizada.
- Reflexionar sobre qué norma proporciona una evaluación más eficiente de la convergencia.

**Salidas:**
1. Número de iteraciones necesarias para alcanzar la tolerancia bajo cada norma.
2. Comparación de la velocidad de convergencia.

**Nota:**

El comando `np.linalg.norm` puede utilizar diferentes normas alterando el valor del parámetro `ord` usando un diccionario, por ejemplo:
```python
norm_types = {'L1': 1, 'L2': 2, 'L∞': np.inf}
```
Más detalles se pueden encontrar en la documentación oficial: [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html).


#### **Métodos Iterativos: método de Gauss-Seidel**

A diferencia del método de Jacobi, el método de Gauss-Seidel utiliza los valores ya calculados de las componentes de la solución en la misma iteración para acelerar la convergencia.

##### **Ejemplo: Aplicación del método de Gauss-Seidel**

**Descripción del problema:**

Resolver el siguiente sistema de ecuaciones:
$$
\left\{
\begin{array}{rcc}
4x_1  -x_2  +2x_3 & = & 15\\
  -3x_2  +x_3 & = & 6\\
-x_1  +2x_2  +5x_3 & = & 11
\end{array}
\right.
$$

**Objetivo:**
- Implementar el método de Gauss-Seidel.
- Obtener aproximaciones sucesivas de la solución.

**Salidas:**
1. Aproximaciones de la solución en cada iteración.

In [ ]:
import numpy as np

def gauss_seidel(A, b, x0, max_iter=10, tol=1e-4):
    """
    Implementa el método de Gauss-Seidel para resolver sistemas lineales Ax = b.

    Parámetros:
    A (ndarray): Matriz de coeficientes (n x n).
    b (ndarray): Vector de términos independientes (n).
    x0 (ndarray): Vector inicial para las iteraciones (n).
    max_iter (int): Número máximo de iteraciones.
    tol (float): Tolerancia para el criterio de convergencia.

    Retorna:
    ndarray: Vector solución aproximada.
    int: Número de iteraciones realizadas.
    """
    n = len(b)  # Número de ecuaciones
    x = x0.copy()  # Inicializamos el vector solución con la aproximación inicial

    for k in range(max_iter):
        x_new = np.copy(x)  # Copia del vector solución para actualizar en la iteración

        for i in range(n):
            # Suma de los términos antes de la diagonal principal
            sum1 = np.dot(A[i, :i], x_new[:i])

            # Suma de los términos después de la diagonal principal
            sum2 = np.dot(A[i, i+1:], x[i+1:])

            # Actualizamos el valor de x[i] usando la fórmula del método de Gauss-Seidel
            x_new[i] = (b[i] - sum1 - sum2) / A[i, i]

        # Verificamos la convergencia usando la norma infinito
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k + 1

        x = x_new  # Actualizamos el vector solución para la siguiente iteración

    return x, max_iter  # Retornamos la última solución y el número máximo de iteraciones

# Definimos la matriz de coeficientes A y el vector de términos independientes b
A = np.array([[4, -1, 2], [0, -3, 1], [-1, 2, 5]], dtype=float)
b = np.array([15, 6, 11], dtype=float)

# Vector inicial (x0) con todos los valores en cero
x0 = np.zeros_like(b)

# Llamamos a la función para resolver el sistema
sol, iteraciones = gauss_seidel(A, b, x0)

# Mostramos la solución aproximada y el número de iteraciones realizadas
print(f"Solución aproximada: {sol}")
print(f"Iteraciones: {iteraciones}")

##### **Ejercicio 1: Implementación del método de Gauss-Seidel**

**Descripción del problema:**

Implemente el método de Gauss-Seidel y aplíquelo a un sistema de ecuaciones de su elección.

**Objetivo:**
- Comprender la implementación del método.
- Experimentar con diferentes matrices y condiciones iniciales.

**Salidas:**
1. Solución aproximada.
2. Número de iteraciones necesarias.

##### **Ejercicio 2: Comparación con el método de Jacobi**

**Descripción del problema:**

Compare la eficiencia del método de Gauss-Seidel con el de Jacobi en términos de iteraciones necesarias y precisión.

**Objetivo:**
- Implementar ambos métodos.
- Evaluar su rendimiento.

**Salidas:**
1. Comparación de iteraciones y errores.

##### **Ejercicio 3 (difícil): Condición de convergencia**

**Descripción del problema:**

Verifique si una matriz dada cumple con el criterio de convergencia para el método de Gauss-Seidel. Aplique el método de Gauss-Seidel al sistema y compare los resultados obtenidos.

**Objetivo:**
- Verificar si la matriz de coeficientes es estrictamente diagonalmente dominante.
- Determinar la convergencia del método de Gauss-Seidel en un caso práctico.

**Salidas:**
1. Mensaje indicando si la matriz cumple el criterio de convergencia.
2. Solución aproximada y número de iteraciones.